### ISSUE TITLE
March 23, 2015 Update.

### ISSUE THREAD

**Issue by ieliopou** [kawannam/SENG_301_BeatTheBasics#2]
+Metronome is almost done.
-Need to create more unit tests for it (out of bounds, inc/dec)
-Need to implement metronome in unity

Plan:
+Figure out MVC
+Finish metronome
+Test integration with unity
+Start Play by Ear

**Comment by kawannam** [comment]
Hello!

You have a new message, please read http://bidding.rlogical.com/error.php?ig2b

kendra wannamaker

**Comment by kawannam** [comment]
Hello friend, 

Have you  ever thought about how  would the cities  of the  future look  like? I  found some   interesting  stuff about that here http://step.gc-impact.com/lnnnsfm

My best to you, kendra wannamaker
